import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';
import divider from '../images/pattern-divider-desktop.svg'
import Image from 'next/image';
import dice from '../images/icon-dice.svg'


export default function Home() {

  const [ quote, setQuote ] = useState({id: "", quote: ""});

  const fetchQuote = async () => {
    const quoteData = await fetch("/api/quote")
    const quoteJSON = await quoteData.json()
    const quoteContent = await quoteJSON.content
    const quoteId = await quoteJSON.id

    if (quoteContent && quoteId) {
      setQuote({...quote, quote: quoteContent, id: quoteId})
    }

  }

  useEffect(() => {
    setQuote(fetchQuote);
  }, [])



  return (
    <>
      <Head>
        <title>advice generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
        <h1 className={styles.header}>ADVICE # {quote.id}</h1>
        <div className={styles.quotecontainer}>
        <div className={styles.quote}>{'"' + quote.quote + '"'}</div>
        </div>
        <Image priority={true} className={styles.divider} src={divider} alt="divider"></Image>
        <button className={styles.quotebutton} onClick={fetchQuote}>
          <Image src={dice} alt="dice"></Image>
        </button>
        </div>
      </main>
  <footer className='attribution'>
    Challenge by <a href="https://www.frontendmentor.io?ref=challenge">Frontend Mentor</a>.
    Coded by <a href="#">Salman Hossain</a>.
  </footer>
    </>
  )
}
